name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      requestor:
        description: "A requestor name"
        default: "pradeep toluganti"
        required: false
        type: string

      datacenter:
        description: "datacenter name"
        default: "dc-01"
        required: false
        type: string

      app_version:
        description: "use Version"
        default: "v1.0.1"
        required: false
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform Code
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0
          ref: ${{ github.event.inputs.app_version }}

      # - name: Checkout TF Vars Repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: JDeeptaTech/tf-vars-repo
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     path: tf-vars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Change script permissions
        run: chmod +x ./scripts/*.sh

      - name: Generate Terraform variables file
        run: ./scripts/generate-tfvars.sh ./src "${{ github.event.inputs.requestor }}" "${{ github.event.inputs.datacenter }}"

      - name: Initialize Terraform
        run: terraform -chdir=src init

      - name: Plan Terraform
        run: ./scripts/tf-plan.sh

      # - name: Apply Terraform (Manual Approval Required)
      #   if: github.event_name == 'workflow_dispatch'
      #   run: terraform apply -auto-approve -var-file=tf-vars/variables.tfvars
